api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ProfileList, ProfileDetail, ProjectList, ProjectDetail

app_name = "api"

urlpatterns = format_suffix_patterns(
    [
        path("profiles/", ProfileList.as_view(), name="profile_list"),
        path("profile/<uuid:pk>/", ProfileDetail.as_view(), name="profile_detail"),
        path("projects/", ProjectList.as_view(), name="project_list"),
        path("project/<uuid:pk>/", ProjectDetail.as_view(), name="project_detail"),
    ]
)

projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"

urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path("project/<uuid:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("project/create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project/update/<uuid:pk>/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "project/delete/<uuid:pk>/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
]

search_dev/urls.py
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import MyObtainTokenPairView

urlpatterns = [
    path("shery-admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("api/", include("api.urls")),
    path("token/", MyObtainTokenPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("users.urls")),
    path("", include("projects.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (
    UserProfileListView,
    UserProfileDetailView,
    UserAccountView,
    UserAccountEditView,
    SkillCreateView,
    SkillUpdateView,
    SkillDeleteView,
    MessageCreateView,
    MessageListView,
    MessageDetailView,
)

app_name = "users"

urlpatterns = [
    path("", UserProfileListView.as_view(), name="users_profiles"),
    path("profile/<uuid:pk>/", UserProfileDetailView.as_view(), name="user_profile"),
    path("account/", UserAccountView.as_view(), name="user_account"),
    path("account/edit/", UserAccountEditView.as_view(), name="user_account_edit"),
    path("create/skill/", SkillCreateView.as_view(), name="skill_create"),
    path("update/skill/<uuid:pk>/", SkillUpdateView.as_view(), name="skill_update"),
    path("delete/skill/<uuid:pk>/", SkillDeleteView.as_view(), name="skill_delete"),
    path(
        "create/message/<uuid:pk>/", MessageCreateView.as_view(), name="message_create"
    ),
    path("inbox/", MessageListView.as_view(), name="inbox"),
    path("message/<uuid:pk>/", MessageDetailView.as_view(), name="message_detail"),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/556e9f70c0.js" crossorigin="anonymous"></script>
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevSearch - {% block title %}{% endblock title %}</title>
  </head>

  <body>

    {% include '_navbar.html' %}
    {% if messages %}
      <ul class="django-messages">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" id="box" style="margin-bottom: 0px;">
            {{ message }}
          </div>
          {% endfor %}
      </ul>
    {% endif %}

    {% block content %}{% endblock content %}

    <script src="{% static 'uikit/app.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
  </body>
</html>

templates/_navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
  <div class="container container--narrow">
    <a href="{% url 'users:users_profiles' %}" class="header__logo">
      <img src="{% static 'img/logo.svg' %}" alt="DevSearch Logo" />
    </a>
    <nav class="header__nav">
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        <li class="header__menuItem">
          <a href="{% url 'users:users_profiles' %}">Developers</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'projects:project_list' %}">Projects</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="header__menuItem">
          <a href="{% url 'users:inbox' %}">Inbox</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'users:user_account' %}">My Account</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'api-docs' %}" target="_blank">API</a>
        </li>
        {% endif %}
        <li class="header__menuItem">
          {% if request.user.is_authenticated %}
            <a href="{% url 'account_logout' %}" class="btn btn--sub">Logout</a>
          {% else %}
            <a href="{% url 'account_login' %}" class="btn btn--sub">Login</a>
            <a href="{% url 'account_signup' %}" class="btn btn--sub">Sign Up</a>
          {% endif %}
        </li>
      </ul>
    </nav>
  </div>
</header>