api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import ProfileList, ProfileDetail, ProjectList, ProjectDetail

app_name = "api"

urlpatterns = format_suffix_patterns(
    [
        path("profiles/", ProfileList.as_view(), name="profile_list"),
        path("profile/<uuid:pk>/", ProfileDetail.as_view(), name="profile_detail"),
        path("projects/", ProjectList.as_view(), name="project_list"),
        path("project/<uuid:pk>/", ProjectDetail.as_view(), name="project_detail"),
    ]
)

projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"

urlpatterns = [
    path("projects/", ProjectListView.as_view(), name="project_list"),
    path("project/<uuid:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("project/create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project/update/<uuid:pk>/",
        ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "project/delete/<uuid:pk>/",
        ProjectDeleteView.as_view(),
        name="project_delete",
    ),
]

search_dev/urls.py
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import MyObtainTokenPairView

urlpatterns = [
    path("shery-admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("api/", include("api.urls")),
    path("token/", MyObtainTokenPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", include("users.urls")),
    path("", include("projects.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (
    UserProfileListView,
    UserProfileDetailView,
    UserAccountView,
    UserAccountEditView,
    SkillCreateView,
    SkillUpdateView,
    SkillDeleteView,
    MessageCreateView,
    MessageListView,
    MessageDetailView,
)

app_name = "users"

urlpatterns = [
    path("", UserProfileListView.as_view(), name="users_profiles"),
    path("profile/<uuid:pk>/", UserProfileDetailView.as_view(), name="user_profile"),
    path("account/", UserAccountView.as_view(), name="user_account"),
    path("account/edit/", UserAccountEditView.as_view(), name="user_account_edit"),
    path("create/skill/", SkillCreateView.as_view(), name="skill_create"),
    path("update/skill/<uuid:pk>/", SkillUpdateView.as_view(), name="skill_update"),
    path("delete/skill/<uuid:pk>/", SkillDeleteView.as_view(), name="skill_delete"),
    path(
        "create/message/<uuid:pk>/", MessageCreateView.as_view(), name="message_create"
    ),
    path("inbox/", MessageListView.as_view(), name="inbox"),
    path("message/<uuid:pk>/", MessageDetailView.as_view(), name="message_detail"),
]

users/models.py
from cloudinary.models import CloudinaryField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import uuid


class Profile(models.Model):
    """Model for User Profile"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name="profile"
    )
    name = models.CharField(max_length=255)
    headline = models.CharField(max_length=255, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    user_img = CloudinaryField(
        null=True,
        blank=True,
        default="https://res.cloudinary.com/dkfgh093c/image/upload/v1675368559/user-default_m9kpsk.png",
    )
    social_github = models.CharField(max_length=255, null=True, blank=True)
    social_twitter = models.CharField(max_length=255, null=True, blank=True)
    social_linkedin = models.CharField(max_length=255, null=True, blank=True)
    social_youtube = models.CharField(max_length=255, null=True, blank=True)
    social_website = models.CharField(max_length=255, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_on", "-created_on"]
        indexes = [models.Index(fields=["id", "-updated_on", "-created_on"])]

    def __str__(self):
        """Defines representation of profile object"""
        return f"{self.user.name}'s profile"

    def get_absolute_url(self):
        """Canonical url for each user profile"""
        return reverse("users:user_profile", args=[self.id])

    @property
    def imageURL(self):
        try:
            url = self.user_img.url
        except:
            url = ""
        return url


class Skill(models.Model):
    """Skill Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="skills")
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Defines representation of skill object"""
        return self.name


class Message(models.Model):
    """Message Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True
    )
    recipient = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="messages",
    )
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    subject = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["is_read", "-updated_on", "-created_on"]

    def __str__(self):
        return self.subject[:50]

    def get_absolute_url(self):
        """Canonical url for each user message"""
        return reverse("users:message_detail", args=[self.id])

users/forms.py
from django import forms
from .models import Profile, Skill, Message


class ProfileForm(forms.ModelForm):
    user_img = forms.ImageField(
        label="Profile Pic",
        required=False,
        error_messages={"invalid": "Image files only"},
        widget=forms.FileInput,
    )

    class Meta:
        model = Profile
        fields = [
            "name",
            "headline",
            "bio",
            "location",
            "user_img",
            "social_github",
            "social_twitter",
            "social_linkedin",
            "social_youtube",
            "social_website",
        ]

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ["name", "description"]

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["name", "email", "subject", "body"]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

users/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import (
    View,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from projects.models import Project
from .models import Profile, Skill, Message

from .forms import ProfileForm, SkillForm, MessageForm


class UserProfileListView(ListView):
    """View to list all the users"""

    model = Profile
    template_name = "users/users_profiles.html"
    context_object_name = "profile_list"
    paginate_by = 6

    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get("q")
        if query:
            skills = Skill.objects.filter(name__icontains=query)
            return Profile.objects.filter(
                Q(headline__icontains=query)
                | Q(name__icontains=query)
                | Q(location__icontains=query)
                | Q(bio__icontains=query)
                | Q(skills__in=skills)
            ).distinct()
        else:
            return Profile.objects.exclude(headline__exact=None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("q")
        return context


class UserProfileDetailView(DetailView):
    """View to display profile in detail"""

    model = Profile
    template_name = "users/user_profile.html"
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["projects"] = sorted(
            Project.objects.filter(owner__id=self.get_object().id),
            key=lambda t: (t.vote_ratio, t.vote_count),
            reverse=True,
        )
        context["skills"] = self.get_object().skills.exclude(description__exact="")
        context["other_skills"] = self.get_object().skills.filter(description__exact="")
        return context


class UserAccountView(View):
    def get(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        return render(request, "users/user_account.html", {"profile": profile})


class UserAccountEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        profile = request.user.profile
        form = ProfileForm(instance=profile)
        context = {"form": form}
        return render(request, "users/user_account_edit.html", context)

    def post(self, request, *args, **kwargs):
        profile = request.user.profile
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            user = request.user
            user_name = form.cleaned_data["name"]
            user.name = user_name
            user.save()
            form.save()
            messages.success(request, "Your profile was updated successfully.")
        else:
            messages.error(
                request, "There was a problem updating your profile. Please try again!"
            )
        return redirect("users:user_account")


class SkillCreateView(LoginRequiredMixin, CreateView):
    form_class = SkillForm
    template_name = "users/skill_create.html"

    def get_success_url(self):
        messages.success(self.request, "Your skill was added successfully.")
        return reverse_lazy("users:user_account")

    def form_valid(self, form):
        form.instance.owner = self.request.user.profile
        form.save()
        return super().form_valid(form)


class SkillUpdateView(LoginRequiredMixin, UpdateView):
    model = Skill
    form_class = SkillForm
    template_name = "users/skill_update.html"

    def get_success_url(self):
        messages.success(self.request, "Your skill was updated successfully.")
        return reverse_lazy("users:user_account")


class SkillDeleteView(LoginRequiredMixin, DeleteView):
    model = Skill
    template_name = "users/skill_delete.html"

    def get_success_url(self):
        messages.error(self.request, "Your skill was deleted successfully.")
        return reverse_lazy("users:user_account")


class MessageListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        recipient = request.user.profile
        new_messages = Message.objects.filter(recipient=recipient, is_read=False)
        old_messages = Message.objects.filter(recipient=recipient, is_read=True)
        context = {"new_messages": new_messages, "old_messages": old_messages}
        return render(request, "users/inbox.html", context)


class MessageDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        message = Message.objects.get(id=kwargs["pk"])
        if message.is_read == False:
            message.is_read = True
            message.save()
        context = {"message": message}
        return render(request, "users/message_detail.html", context)


class MessageCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        recipient = Profile.objects.get(id=kwargs.get("pk"))
        form = MessageForm()
        context = {"recipient": recipient, "form": form}
        return render(request, "users/message_create.html", context)

    def post(self, request, *args, **kwargs):
        recipient = Profile.objects.get(id=kwargs.get("pk"))
        try:
            sender = request.user.profile
        except:
            sender = None

        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.user.name
                message.email = sender.user.email

            message.save()
            messages.success(request, "Your message was sent.")
        else:
            messages.error(
                request, "There was a problem sending your message. Please try again!"
            )

        return redirect("users:user_profile", pk=recipient.id)

templates/users/create_skill.html
{% extends '_base.html' %}

{% block title %}Skill Form{% endblock title %}


{% block content %}

    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'users:user_account' %}"><i class="fa-solid fa-angle-left"></i></a>
                <br>

                <form class="form" method="POST" action="">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text"> {{field.label}}</label>
                        {{field}}
                    </div>
                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>



{% endblock content %}

templates/users/message_detail.html
{% extends '_base.html' %}

{% block title %}Message{% endblock title %}

{% block content %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:inbox' %}"><i class="fa-solid fa-angle-left"></i></a>
        <h2 class="message__subject">{{ message.subject|capfirst }}</h4>
          <a href="{% url 'users:user_profile' message.sender.id %}" class="message__author">{{ message.name|title }}</a>
          <p class="message__date">{{ message.created_on }}</p>
          <div class="message__body">
            {{ message.body|linebreaks }}
          </div>
      </div>
    </div>
  </main>

{% endblock content %}

templates/users/user_account.html
{% extends '_base.html' %}

{% block title %}User Account{% endblock title %}

{% block content %}

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:user_account_edit' %}">
                <i class="fa-solid fa-pen-to-square fa-fw"></i> Edit
              </a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.imageURL }}" />
              {% if request.user.name or profile.name %}
                <h2 class="dev__name">{{  request.user.name|title }}</h2>
              {% endif %}
              {% if profile.headline %}
                <p class="dev__title">{{ profile.headline }}</p>
              {% endif %}
              {% if profile.location %}
                <p class="dev__location">Based in {{ profile.location }}</p>
              {% endif %}
              <ul class="dev__social">
                {% if profile.social_github %}
                  <li>
                    <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fa-brands fa-github fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_youtube %}
                  <li>
                    <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fa-brands fa-youtube fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_twitter %}
                  <li>
                    <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="fa-brands fa-twitter fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_linkedin %}
                  <li>
                    <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_website %}
                  <li>
                    <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa-solid fa-globe fa-2x"></i></a>
                  </li>
                {% endif %}
              </ul>
              {% if request.user != profile.user %}
                <a href="{% url 'users:message_create' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            {% if profile.bio %}
              <p class="devInfo__about">
                {{ profile.bio|linebreaks }}
              </p>
            {% endif %}
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:skill_create' %}">
              <i class="fa-sharp fa-solid fa-plus fa-fw"></i> Add Skill
            </a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skills.all %}
              <tr>
                <td class="settings__tableInfo">
                  <h4>{{ skill.name|title }}</h4>
                  <p>
                    {{ skill.description|linebreaks|truncatewords:100 }}
                  </p>
                </td>
                <td class="settings__tableActions">
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:skill_update' skill.id %}"><i class="fa-solid fa-pen-to-square fa-fw"></i> Edit</a>
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:skill_delete' skill.id %}"><i class="fa-solid fa-circle-xmark fa-fw"></i>
                    Delete</a>
                </td>
              </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:project_create' %}">
              <i class="fa-sharp fa-solid fa-plus fa-fw"></i> Add Project
            </a>
          </div>

          <table class="settings__table">
          {% for project in profile.projects.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{{ project.get_absolute_url }}"><img src="{{ project.imageURL }}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{{ project.get_absolute_url }}">{{ project.headline|title }}</a>
                <p>
                  {{ project.description|linebreaks|truncatewords:20 }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:project_update' project.id %}"><i class="fa-solid fa-pen-to-square fa-fw"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:project_delete' project.id %}"><i class="fa-solid fa-circle-xmark fa-fw"></i>
                  Delete</a>
              </td>
            </tr>
          {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main> 

{% endblock content %}

templates/users/user_profile.html
{% extends '_base.html' %}

{% block title %}{{ profile.name }}'s Profile{% endblock title %}

{% block content %}
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.imageURL }}" />
              <h2 class="dev__name">{{ profile.name|title }}</h2>
              {% if profile.headline %}
                <p class="dev__title">{{ profile.headline|title }}</p>
              {% endif %}
              {% if profile.location %}
                <p class="dev__location">Based in {{ profile.location }}</p>
              {% endif %}
              <ul class="dev__social">
                {% if profile.social_github %}
                  <li>
                    <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="fa-brands fa-github fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_youtube %}
                  <li>
                    <a title="Youtube" href="{{ profile.social_youtube }}" target="_blank"><i class="fa-brands fa-youtube fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_twitter %}
                  <li>
                    <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="fa-brands fa-twitter fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_linkedin %}
                  <li>
                    <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_website %}
                  <li>
                    <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="fa-solid fa-globe fa-2x"></i></a>
                  </li>
                {% endif %}
              </ul>
              {% if request.user != profile.user %}
                <a href="{% url 'users:message_create' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
              </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio|linebreaks }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in skills %}
                <div class="devSkill">
                    <h4 class="devSkill__title">{{ skill.name }}</h4>
                    <p class="devSkill__info">
                    {{ skill.description }}
                    </p>
                </div>
              {% endfor %}

                {% if other_skills %}
                  <h3 class="devInfo__subtitle">Other Skills</h3>
                  <div class="devInfo__otherSkills">
                      {% for skill in other_skills %}
                        <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{ skill.name }}</small>
                        </span>
                    {% endfor %}
                  </div>
              {% endif %}
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              {% for project in projects %}
                <div class="column">
                    <div class="card project">
                      <a href="{{ project.get_absolute_url }}" class="project">
                          <img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail" />
                          <div class="card__body">
                          <h3 class="project__title">{{ project.title|title }}</h3>
                          <p><a class="project__author" href="{{ project.profile.get_absolute_url }}">By {{ project.owner.name|title }}</a></p>
                          <p class="project--rating">
                              <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                              Feedback ({{ project.vote_count }} Vote{{ project.vote_count|pluralize }})
                          </p>
                          <div class="project__tags">
                              {% for tag in project.tags.all|slice:":5" %}
                                  <span class="tag tag--pill tag--main">
                                  <small>{{ tag.name }}</small>
                                  </span>
                              {% endfor %}
                          </div>
                          </div>
                      </a>
                    </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

templates/users/users_profiles.html
{% extends '_base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <main class="home">
      <section class="hero-section text-center">
        <div class="container container--narrow">
          <div class="hero-section__box">
            <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
            <h2>FROM AROUND THE WORLD</h2>
          </div>

          <div class="hero-section__search">
            <form class="form" action="{% url 'users:users_profiles' %}" method="get">
              <div class="form__field">
                <label for="formInput#search">Search Developers </label>
                <input
                  class="input input--text"
                  id="formInput#search"
                  type="text"
                  name="q"
                  placeholder="Search by developer name"
                />
              </div>

              <input
                class="btn btn--sub btn--lg"
                type="submit"
                value="Search"
              />
            </form>
          </div>
        </div>
      </section>
      <!-- Search Result: DevList -->
      {% if query %}
      <h4 class="text-center">Search Results ({{ profile_list.count }} Profile{{ profile_list.count|pluralize }} Found)</h1>
      {% endif %}
      <section class="devlist">
        <div class="container">
          <div class="grid grid--three">
            {% for profile in profile_list %}
                <div class="column card">
                  <div class="dev">
                      <a href="{{ profile.get_absolute_url }}" class="card__body">
                      <div class="dev__profile">
                          <img
                          class="avatar avatar--md"
                          src="{{ profile.imageURL }}"
                          alt="image"
                          />
                          <div class="dev__meta">
                          <h3>{{ profile.name|title }}</h3>
                          <h5>{{ profile.headline|title }}</h5>
                          </div>
                      </div>
                      <p class="dev__info">
                          {{ profile.bio|linebreaks|truncatewords:50 }}
                      </p>
                      <br>
                      <div class="dev__skills">
                          {% for skill in profile.skills.all|slice:":5" %}
                              <span class="tag tag--pill tag--main">
                              <small>{{ skill.name|upper }}</small>
                              </span>
                          {% endfor %}
                      </div>
                      </a>
                  </div>
                </div>
            {% endfor %}
          </div>
        </div>
      </section>

      {% if profile_list %}
        <div class="pagination">
          <ul class="container">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="btn">&#10094; Prev</a></li>
            {% else %}
                <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if i == page_obj.number %}
                    <li><a href="?page={{ i }}" class="btn btn--sub">{{ i }}</a></li>
                {% else %}
                    <li><a href="?page={{ i }}" class="btn">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn">Next &#10095;</a></li>
            {% else %}
                <li><a href="#" class="btn btn--disabled">Next &#10095;</a></li>
            {% endif %}
          </ul>
        </div>
      {% endif %}
    </main>

{% endblock content %}